name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json' # optionnel mais recommandé

      - name: Install Node Dependencies
        run: |
          npm install -g tailwindcss postcss autoprefixer
          npm install tailwindcss postcss autoprefixer

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: npx tailwindcss -i ./assets/css/main.css -o ./assets/css/dist.css --minify || true && hugo --gc --minify
        # Note : Nous forçons l'initialisation de Tailwind via npx, puis nous lançons la compilation Hugo classique.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
